# Generated by Django 4.2.7 on 2024-01-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techwaveapp', '0004_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techsupportservice',
            name='price',
        ),
        migrations.AddField(
            model_name='techsupportservice',
            name='description',
            field=models.TextField(default='Default description for the service.'),
        ),
    ]
